### ISSUE TITLE
Usage on the focal loss

### ISSUE THREAD

**Issue by briansodenkin** [AdeelH/pytorch-multi-class-focal-loss#5]
I tried to replace the F.Cross_Entropy(out, target) with focal_loss(out, target), however, there is problem in the weight tensor.
In the implementation, it will call the ce = self.nll_loss(log_p, y).
But there will be problem:
RuntimeError: weight tensor should be defined either for all _ classes or no classes but got weight tensor of shape:[2]

It seems that the code is not applicable on the latest version of Pytorch ?

**Comment by AdeelH** [comment]
Thanks for the report. I was not able to reproduce this error using this notebook: https://colab.research.google.com/drive/1iiZh1eei5UTyBuxE5b_Y4D8lom1j5XAh?usp=sharing

Can you share the full code snippet where you are importing this focal loss module and also the full stack trace of the error?

**Comment by briansodenkin** [comment]
from tqdm import tqdm
import argparse
import torch.optim as optim
from data_loader import get_loader
from utils import accuracy, Tracker
from coral import coral
from focal_loss import FocalLoss, focal_loss

def train(model, optimizer, source_loader, target_loader, tracker, args, epoch=0):

    model.train()
    tracker_class, tracker_params = tracker.MovingMeanMonitor, {'momentum': 0.99}

    # Trackers to monitor classification and CORAL loss
import torch.optim as optim
from data_loader import get_loader
from utils import accuracy, Tracker
from coral import coral
from focal_loss import FocalLoss, focal_loss

def train(model, optimizer, source_loader, target_loader, tracker, args, epoch=0):

    model.train()
    tracker_class, tracker_params = tracker.MovingMeanMonitor, {'momentum': 0.99}

    # Trackers to monitor classification and CORAL loss
    classification_loss_tracker = tracker.track('classification_loss', tracker_class(**tracker_params))
    coral_loss_tracker = tracker.track('CORAL_loss', tracker_class(**tracker_params))

    min_n_batches = min(len(source_loader), len(target_loader))

    tq = tqdm(range(min_n_batches), desc='{} E{:03d}'.format('Training + Adaptation', epoch), ncols=0)

    for _ in tq:

        source_data, source_label = next(iter(source_loader))
        target_data, _ = next(iter(target_loader))  # Unsupervised Domain Adaptation

        source_data, source_label = Variable(source_data.to(device=args.device)), Variable(source_label.to(device=args.device))
        target_data = Variable(target_data.to(device=args.device))

        optimizer.zero_grad()

        out_source = model(source_data)
        out_target = model(target_data)
        alpha = torch.tensor([.75, .25])
        gamma = 2
        focal_loss = torch.hub.load(repo_or_dir='adeelh/pytorch-multi-class-focal-loss',model='focal_loss',alpha=[.75, .25],gamma=2,reduction='mean',device='cpu',dtype=torch.float32,force_reload=False)
        coral_loss = coral(out_source, out_target)
        classification_loss = focal_loss(out_source, source_label)
        composite_loss = classification_loss + 0.5 * coral_loss
        composite_loss.backward()
        optimizer.step()

        classification_loss_tracker.append(classification_loss.item())
        coral_loss_tracker.append(coral_loss.item())
        fmt = '{:.4f}'.format
        tq.set_postfix(classification_loss=fmt(classification_loss_tracker.mean.value),
                       coral_loss=fmt(coral_loss_tracker.mean.value))

**Comment by briansodenkin** [comment]
Here is the code
`from tqdm import tqdm
import argparse
import torch.optim as optim
from data_loader import get_loader
from utils import accuracy, Tracker
from coral import coral
from focal_loss import FocalLoss, focal_loss

def train(model, optimizer, source_loader, target_loader, tracker, args, epoch=0):

    model.train()
    tracker_class, tracker_params = tracker.MovingMeanMonitor, {'momentum': 0.99}

    # Trackers to monitor classification and CORAL loss
import torch.optim as optim
from data_loader import get_loader
from utils import accuracy, Tracker
from coral import coral
from focal_loss import FocalLoss, focal_loss

def train(model, optimizer, source_loader, target_loader, tracker, args, epoch=0):

    model.train()
    tracker_class, tracker_params = tracker.MovingMeanMonitor, {'momentum': 0.99}

    # Trackers to monitor classification and CORAL loss
    classification_loss_tracker = tracker.track('classification_loss', tracker_class(**tracker_params))
    coral_loss_tracker = tracker.track('CORAL_loss', tracker_class(**tracker_params))

    min_n_batches = min(len(source_loader), len(target_loader))

    tq = tqdm(range(min_n_batches), desc='{} E{:03d}'.format('Training + Adaptation', epoch), ncols=0)

    for _ in tq:

        source_data, source_label = next(iter(source_loader))
        target_data, _ = next(iter(target_loader))  # Unsupervised Domain Adaptation

        source_data, source_label = Variable(source_data.to(device=args.device)), Variable(source_label.to(device=args.device))
        target_data = Variable(target_data.to(device=args.device))

        optimizer.zero_grad()

        out_source = model(source_data)
        out_target = model(target_data)
        alpha = torch.tensor([.75, .25])
        gamma = 2
        # classification_loss = F.cross_entropy(out_source, source_label)
        # pt = torch.exp(-classification_loss)
        # classification_loss = ((1-pt) ** 2 * classification_loss).mean()
        # focal_loss = FocalLoss(alpha, gamma)
        # classification_loss = focal_loss(out_source, source_label)
        # This is where the magic happens
        focal_loss = torch.hub.load(repo_or_dir='adeelh/pytorch-multi-class-focal-loss',model='focal_loss',alpha=[.75, .25],gamma=2,reduction='mean',device='cpu',dtype=torch.float32,force_reload=False)
        coral_loss = coral(out_source, out_target)
        classification_loss = focal_loss(out_source, source_label)
        composite_loss = classification_loss + args.lambda_coral * coral_loss
        composite_loss.backward()
        optimizer.step()

        classification_loss_tracker.append(classification_loss.item())
        coral_loss_tracker.append(coral_loss.item())
        fmt = '{:.4f}'.format
        tq.set_postfix(classification_loss=fmt(classification_loss_tracker.mean.value),
                       coral_loss=fmt(coral_loss_tracker.mean.value))`

**Comment by briansodenkin** [comment]
```python
from torchvision.models import alexnet
from torchvision.models import resnet50
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F
from tqdm import tqdm
import argparse
import torch.optim as optim
from data_loader import get_loader
from utils import accuracy, Tracker
from coral import coral
from focal_loss import FocalLoss, focal_loss

def train(model, optimizer, source_loader, target_loader, tracker, args, epoch=0):

    model.train()
    tracker_class, tracker_params = tracker.MovingMeanMonitor, {'momentum': 0.99}

    # Trackers to monitor classification and CORAL loss
    classification_loss_tracker = tracker.track('classification_loss', tracker_class(**tracker_params))
    coral_loss_tracker = tracker.track('CORAL_loss', tracker_class(**tracker_params))

    min_n_batches = min(len(source_loader), len(target_loader))

    tq = tqdm(range(min_n_batches), desc='{} E{:03d}'.format('Training + Adaptation', epoch), ncols=0)

    for _ in tq:

        source_data, source_label = next(iter(source_loader))
        target_data, _ = next(iter(target_loader))  # Unsupervised Domain Adaptation

        source_data, source_label = Variable(source_data.to(device=args.device)), Variable(source_label.to(device=args.device))
        target_data = Variable(target_data.to(device=args.device))

        optimizer.zero_grad()

        out_source = model(source_data)
        out_target = model(target_data)
        alpha = torch.tensor([.75, .25])
        gamma = 2
        # classification_loss = F.cross_entropy(out_source, source_label)
        # pt = torch.exp(-classification_loss)
        # classification_loss = ((1-pt) ** 2 * classification_loss).mean()
        # focal_loss = FocalLoss(alpha, gamma)
        # classification_loss = focal_loss(out_source, source_label) 
        # This is where the magic happens
        focal_loss = torch.hub.load(repo_or_dir='adeelh/pytorch-multi-class-focal-loss',model='focal_loss',alpha=[.75, .25],gamma=2,reduction='mean',device='cpu',dtype=torch.float32,force_reload=False)
        coral_loss = coral(out_source, out_target)
        classification_loss = focal_loss(out_source, source_label)
        composite_loss = classification_loss + args.lambda_coral * coral_loss
        composite_loss.backward()
        optimizer.step()

        classification_loss_tracker.append(classification_loss.item())
        coral_loss_tracker.append(coral_loss.item())
        fmt = '{:.4f}'.format
        tq.set_postfix(classification_loss=fmt(classification_loss_tracker.mean.value),
                       coral_loss=fmt(coral_loss_tracker.mean.value))


def evaluate(model, data_loader, dataset_name, tracker, args, epoch=0):
    model.eval()

    tracker_class, tracker_params = tracker.MeanMonitor, {}
    acc_tracker = tracker.track('{}_accuracy'.format(dataset_name), tracker_class(**tracker_params))

    loader = tqdm(data_loader, desc='{} E{:03d}'.format('Evaluating on %s' % dataset_name, epoch), ncols=0)

    accuracies = []
    with torch.no_grad():
        for target_data, target_label in loader:
            target_data = Variable(target_data.to(device=args.device))
            target_label = Variable(target_label.to(device=args.device))

            output = model(target_data)

            accuracies.append(accuracy(output, target_label))

            acc_tracker.append(sum(accuracies)/len(accuracies))
            fmt = '{:.4f}'.format
            loader.set_postfix(accuracy=fmt(acc_tracker.mean.value))
```

**Comment by briansodenkin** [comment]
The error produced:
```
Traceback (most recent call last):
  File "/Users/tsangtszkin/Library/Mobile Documents/com~apple~CloudDocs/fyp/robustness_check/PyTorch-Deep-CORAL/train.py", line 161, in <module>
    main()
  File "/Users/tsangtszkin/Library/Mobile Documents/com~apple~CloudDocs/fyp/robustness_check/PyTorch-Deep-CORAL/train.py", line 152, in main
    train(model, optimizer, source_train_loader, target_train_loader, tracker, args, i)
  File "/Users/tsangtszkin/Library/Mobile Documents/com~apple~CloudDocs/fyp/robustness_check/PyTorch-Deep-CORAL/train.py", line 50, in train
    classification_loss = focal_loss(out_source, source_label)
  File "/Users/tsangtszkin/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tsangtszkin/Library/Mobile Documents/com~apple~CloudDocs/fyp/robustness_check/PyTorch-Deep-CORAL/focal_loss.py", line 72, in forward
    ce = self.nll_loss(log_p, y)
  File "/Users/tsangtszkin/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tsangtszkin/miniconda3/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 211, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/Users/tsangtszkin/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2671, in nll_loss
    return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: weight tensor should be defined either for all 1000 classes or no classes but got weight tensor of shape: [2]
```

**Comment by AdeelH** [comment]
The `alpha` param represents class weights. `alpha = [.75, .25]` is an example for the case of 2 classes; it means 0.75 for the first class and 0.25 for the second class. Since you have 1000 classes, you need to provide an alpha with 1000 entries. If you do not want to use different class weights but only want to use `gamma`, you can set alpha to `None`. Please refer to the RetinaNet paper for more details on what the `alpha` and `gamma` mean.
